global:
  ingressSubdomain: workshop-ocp46-three-bb0dafd08526894d1a8ae848e8bd8099-0000.eu-gb.containers.appdomain.cloud
  tlsSecretName: workshop-ocp46-three-bb0dafd08526894d1a8ae848e8bd8099-0000

# replace <app-chart-name> with the value given in requirements.yaml
finance-t1:
  # provides values from the values.yaml in the <app-chart-name> helm chart
  replicaCount: 1
  
  # For OpenShift set route.enabled=true
  # For Kubernetes set route.enabled=false
  route:
    enabled: true
  
  # For OpenShift set ingress.enabled=false
  # For Kubernetes set ingress.enabled=true
  ingress:
    enabled: false
    tlsSecretName: workshop-ocp46-three-bb0dafd08526894d1a8ae848e8bd8099-0000
